attire:
  active: Lucho enciende las luces
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  disabled:
  visible:
    - Procedimientos primitivos
    - Mis procedimientos
    - RepeticionSimple
    - Direccion
    - Numero
    - procedures_defnoreturnnoparams
    - Definicion de procedimientos simples
board:
  active: 1
  initial_board_source: selected
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
name: Lucho enciende las luces
