name: El mono cuenta de nuevo
attire:
  active: El mono y las frutas
  user_permissions:
    can_toggle_visibility: true
  visible: true
blocks:
  defaultToolbox: |
    <category name="Comandos básicos">
        <block type="AlternativaSimple"></block>
        <block type="RepeticionSimple"></block>
        <block type="RepeticionCondicional"></block>
        <block type="Asignacion"></block>
    </category>
    <category name="Expresiones básicas">
        <block type="math_number"></block>
        <block type="DireccionSelector"></block>
        <block type="OperadorNumerico"></block>
        <block type="OperadorLogico"></block>
        <block type="not"></block>
    </category>
    <category name="Operaciones del mono">
        <block type="MoverAlMonoAl_"></block>
        <block type="estáElMonoEnElFinDeLaFila"></block>
        <block type="nroBananas"></block>
        <block type="TildarLasBananas"></block>
        <block type="InformarCantidadDeBananas_"></block>
    </category>
    <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
    <category name="Definiciones">
        <block type="procedures_defnoreturn"></block>
        <block type="procedures_defreturnsimplewithparams"></block>
    </category>
board:
  active: 1
  initial_board_source: random
  visible_edition: false
  collapse_toolbox: false
  user_permissions:
    can_view_attire_section: false
    can_edit_board: false
    can_change_initial_board: false
    can_change_initial_board_source: false
    can_view_size_section: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.65  